self.addEventListener("install",event=>self.skipWaiting());
self.addEventListener("activate",event=>{
  event.waitUntil(
    caches.keys()
      .then(keys=>Promise.all(keys.filter(key=>key.includes("interview")||key.includes("vosk")||key.includes("whisper")).map(key=>caches.delete(key))))
      .then(()=>self.registration.unregister())
      .then(()=>self.clients.claim())
  );
});
self.addEventListener("fetch",()=>{});
